### PR TITLE
Stopping control plane on HA

### PR DESCRIPTION
**Pull request by ktsakalozos**
Only the dqlite voters will run the controller manager and the scheduler. Running three instances of those services should be enough.

### CODE REVIEW

**Comment by balchua** [comment]
I'd like to understand a bit more about dqlite voters.  Say i have 5 node clusters.  How many are voters and how many are standby?

**Comment by ktsakalozos** [comment]
> Say i have 5 node clusters. How many are voters and how many are standby?

3 nodes are voter nodes
2 nodes are stand-by nodes
the rest are spare nodes

Voter nodes replicate the DB and form the cohort in DB maintenance
Stand-by nodes replicate the DB but do not take part in the DB maintenance
Spare nodes neither replicate nor maintain the DB

**Comment by balchua** [comment]
Thanks. Is the 3 node voters and 2 node spares are the maximum it will have? What happens to 7 node cluster?
What do spares do? Do the spares become voters or standbys when some nodes become unhealthy/unresponsive for a prolonged period?
Thanks again for your response.

**Comment by ktsakalozos** [comment]
> What happens to 7 node cluster?

A cluster of n nodes with n > 5 will have 3 voters, 2 standbys and (n-5) spare nodes.

In case a "standby" node leaves the cluster a "spare" one takes its place. Similarly, when a "voter" leaves the cluster a "standby" node will take its place.

**Comment by balchua** [comment]
Great. Thanks for the explanation.  As i understand in this pr, the `controller-manager` and `scheduler` are only needed on nodes which are voters while `apiserver` must run on all nodes.

It would be nice to have the explanation of what the voters, standbys and spares in the documentation.  Just like you did, who takes over who.

Regarding this PR, if it is a single node cluster, the `control-plane-kicker` is running, but doesn't stop the 2 services (`controller-manager` and `scheduler`).

**Comment by ktsakalozos** [comment]
In a cluster at any time there has to be at least one scheduler and controller-manager. This PR makes sure the two services run on nodes acting as dqlite voters. As a result we run three schedulers and controller-managers in total.

**Comment by balchua** [comment]
Thanks @ktsakalozos for the explanation.  This is great for constrained environments.

**Comment by ktsakalozos** [comment]
thank you for the review and feedback.

**Pull request merged**
