### PR TITLE
Add building from source doc

### PR DESCRIPTION
**Pull request by evilnick**
This adds the 'building from source' documentation as a standalone page.

* rewritten as steps
* added link to Snapcraft docs

@ktsakalozos my intention here is to add some standalone pages (one PR at a time) and then adapt the readme to take them into account.

The readme and the final website docs will be slightly different (we don't have side navigation in the readme) but not too much. Making the changes here should improve the docs in this repo and make it easier to sync with the published docs online

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Should we remove the build instructions from the main README and add a link to this work?

**Comment by evilnick** [comment]
@ktsakalozos I'd rather land the separate pieces and then rework the readme - there are a few more pages to go, so it'll be easier just to rewrite the readme once

**Comment by ktsakalozos** [comment]
Fair enough

**Comment by ktsakalozos** [comment]
LGTM +1

**Comment by ktsakalozos** [comment]
> there are a few more pages to go

Could you give us an idea on what is coming?

**Comment by evilnick** [comment]
The other parts from that outline doc ;)
I'll do the add-ons page next

**Pull request merged**
