### PR TITLE
Feature/contd141

### PR DESCRIPTION
**Pull request by tbertenshaw**
Wanting to test cgroups v2 support which would need containerd >= 1.4  so i replicated the pr from @Richard87 (#1695)  in Issue #651. On this codebase which is currently K8s 1.20
 I am trying to test this on a ubuntu 20:10 Pi cluster, unfortunately the artifacts from the github action checks output an amd64 compatible snap. It needs an arm64 snap 😞

### CODE REVIEW

**Comment by Richard87** [comment]
Did you find a way to specify default runtime to `io.containerd.runc.v2`?

**Comment by tbertenshaw** [comment]
> Did you find a way to specify default runtime to `io.containerd.runc.v2`?



> Did you find a way to specify default runtime to `io.containerd.runc.v2`?
when i tried originally was using the steps you specified after having installed the snap.

by editing `/var/snap/microk8s/current/args/containerd-template.toml`

**Comment by ktsakalozos** [comment]
Thank you for this PR @tbertenshaw. Any reason why you did not go for the latest on the 1.4 releases? I see the containerd version you set is v1.4.1, but there is already a v1.4.3 release [1].

> unfortunately the artifacts from the github action checks output an amd64 compatible snap. It needs an arm64 snap

Yes, the GH actions build the snap for AMD64. You could try to build the snap yourself on ARM64 or request a remote build from launchpad builders with `snapcraft remote-build --build-on=amd64,arm64` [2].

[1] https://github.com/containerd/containerd/releases/tag/v1.4.3
[2] https://snapcraft.io/docs/remote-build

**Comment by tbertenshaw** [comment]
> Thank you for this PR @tbertenshaw. Any reason why you did not go for the latest on the 1.4 releases? I see the containerd version you set is v1.4.1, but there is already a v1.4.3 release [1].

Can change to use 1.4.3. But thought that since K8s 1.20 was using 1.4.1 was an easier choice to aline with that.

**Comment by ktsakalozos** [comment]
> Can change to use 1.4.3. But thought that since K8s 1.20 was using 1.4.1 was an easier choice to aline with that.

This PR will be available to the latest/edge and latest/beta channels and will be released to stable with the 1.21 k8s release. I am not sure what v1.21 will be supporting but the latest containerd seems a safe choice.

**Comment by tbertenshaw** [comment]
> > Can change to use 1.4.3. But thought that since K8s 1.20 was using 1.4.1 was an easier choice to aline with that.
> 
> This PR will be available to the latest/edge and latest/beta channels and will be released to stable with the 1.21 k8s release. I am not sure what v1.21 will be supporting but the latest containerd seems a safe choice.

Ok Cool, have just updated to that commit.

**Review by ktsakalozos — APPROVED** [review]
LGTM +1 thank you @tbertenshaw

**Comment by balchua** [comment]
Based on containerd v1.4.3 runc version is v1.0.0-rc92

Usually i look at their [vendor.conf](https://github.com/containerd/containerd/blob/release/1.4/vendor.conf)
I think we should align with it.

**Comment by ktsakalozos** [comment]
> Based on containerd v1.4.3 runc version is v1.0.0-rc92

You are right @balchua, I think that we already have runc v1.0.0-rc92, [1, 2]


[1] https://github.com/ubuntu/microk8s/blob/master/build-scripts/set-env-variables.sh#L22
[2] https://github.com/opencontainers/runc/commit/ff819c7e9184c13b7c2607fe6c30ae19403a7aff

**Comment by tbertenshaw** [comment]
Cool was just cross referencing that also. So no changes needed 😃

**Comment by balchua** [comment]
Thanks @ktsakalozos and @tbertenshaw , i think my brain is fried or my eyes are failing me. 😀

**Pull request merged**
