### PR TITLE
Remove ingress default backend deployment, service and argument

### PR DESCRIPTION
**Pull request by JorritSalverda**
Fixes https://github.com/ubuntu/microk8s/issues/457

### CODE REVIEW

**Comment by JorritSalverda** [comment]
Would you like me to add instructions somewhere on how to clean up the old deployment and service? And if so what would be a good place?

**Comment by balchua** [comment]
@JorritSalverda you probably need to also update the arm64 version too.

**Comment by balchua** [comment]
@JorritSalverda there's also a bunch of tests related to ingress in https://github.com/ubuntu/microk8s/blob/8cbb4d30f5850fc29e25d09ee207f2f85f3fb233/tests/validators.py#L79.  currently it checks the default-http-backend pod if its running or not.

**Comment by ktsakalozos** [comment]
> Would you like me to add instructions somewhere on how to clean up the old deployment and service? And if so what would be a good place?

To do a proper cleanup we should keep the backend related parts of the old `ingress.yaml` in an `ingress-backend.yaml` and when we do a `microk8s.disable ingress` delete that just in case we are transitioning from an "old" ingress to a "new" one. The file you will need to patch is https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/disable.ingress.sh#L21

**Comment by balchua** [comment]
If no one mind, I am continuing this PR. https://github.com/ubuntu/microk8s/pull/619

**Comment by balchua** [comment]
@ktsakalozos @JorritSalverda i think we can close this PR, since #619 is merged.

**Pull request closed without merging**
