### PR TITLE
Update CNI plugins

### LINKED ISSUE #2019: Update CNI to 0.9.0 - enable auto master selection
CNI 0.9.0 added support to automatically select the master NIC - this is very useful when running microk8s & multus in clusters with different NIC names.

It also avoids having to either manually rename the NICs or creating bridges.

https://v0-9-0.cni.dev/plugins/main/macvlan/

Also the documentaion that can be found online points to this capability so it was not obvious to debug until I noticed that `master` was only done optional in the latest version.

If desired I can do the PR - that part is rather easy .

### PR DESCRIPTION
**Pull request by angelnu**
CNI 0.9.0 added support to automatically select the master NIC - this is very useful when running microk8s & multus in clusters with different NIC names.

It also avoids having to either manually rename the NICs or creating bridges.

Fixes: https://github.com/ubuntu/microk8s/issues/2019

*Also verify you have:*
* [x] Read the [contributions](https://github.com/ubuntu/microk8s/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you for this PR @angelnu .

Would you be fine if we update to v0.8.7 [1] instead of v0.9.1? The reason is that Kubernetes has currently v0.8.7 as its build dependency [2]. 

[1] https://github.com/containernetworking/plugins/releases/tag/v0.8.7 
[2] https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml#L46

**Comment by ktsakalozos** [comment]
@angelnu would cni pluging v0.8.7 [1] be fine for your case?

[1] https://github.com/containernetworking/plugins/releases/tag/v0.8.7

**Comment by angelnu** [comment]
Sorry, I missed you first reply...

Yes, 0.8.7 should work since it supports optional masters: https://v0-8-7.cni.dev/plugins/main/macvlan/

**Review by ktsakalozos — APPROVED** [review]
LGTM +1 thank you @angelnu

**Pull request merged**
