### PR TITLE
Add link to Cilium MicroK8s guide

### PR DESCRIPTION
**Pull request by joestringer**
There's a short guide in the Cilium docs about how to bootstrap microk8s with Cilium providing the networking/security as a CNI. Add it to the community links.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
LGTM +1 Thank you @joestringer

**Comment by ktsakalozos** [comment]
I wonder if it would be better to have Cilium as an addon. If you put the installation instructions in a script under https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/ and name it `enable.cilium.sh` you would just need to do a `microk8s.enable cilium`.

**Comment by joestringer** [comment]
@ktsakalozos ah, that sounds like a potentially good approach, I'll look into it.

**Comment by joestringer** [comment]
Here's the PR for the above functionality: https://github.com/ubuntu/microk8s/pull/594

**Pull request merged**
