### PR TITLE
Fix addon extensions

### LINKED ISSUE #1241: Python addons should be able to use the python extension
This line prevents the use of python extension on files for addons. For example, enable.kubeflow.sh is a python addon, but uses the bash extension because of how the wrapper is configured. An option would be to look for addons with either .sh or .py extensions.  https://github.com/ubuntu/microk8s/blob/c256d7a007e2d5a6620196e778839d4dc9499064/microk8s-resources/wrappers/microk8s-enable.wrapper#L38

### PR DESCRIPTION
**Pull request by krisstern**
### *I am verifying that I have:*
* [x] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

### Details
This PR fixes #1241. It addressed the following problems:
1. It enables the use of python extension on files for addons.
2. It renames the microk8s-resources/actions/enable.kubeflow.sh file to microk8s-resources/actions/enable.kubeflow.py to properly reflect the code used for that module.

### CODE REVIEW

**Comment by krisstern** [comment]
I have run the following tests as described in https://github.com/ubuntu/microk8s/pull/1248#issuecomment-636053002 and found the output to be consistent with expectations to the best of my understanding: 

```shell
(microk8s) user@kris-workstation:~/PycharmProjects/microk8s$ sudo microk8s.enable ingress
Enabling Ingress
ingressclass.networking.k8s.io/public created
namespace/ingress created
serviceaccount/nginx-ingress-microk8s-serviceaccount created
clusterrole.rbac.authorization.k8s.io/nginx-ingress-microk8s-clusterrole created
role.rbac.authorization.k8s.io/nginx-ingress-microk8s-role created
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress-microk8s created
rolebinding.rbac.authorization.k8s.io/nginx-ingress-microk8s created
configmap/nginx-load-balancer-microk8s-conf created
configmap/nginx-ingress-tcp-microk8s-conf created
configmap/nginx-ingress-udp-microk8s-conf created
daemonset.apps/nginx-ingress-microk8s-controller created
Ingress is enabled

(microk8s) user@kris-workstation:~/PycharmProjects/microk8s$ sudo microk8s.enable dns
Enabling DNS
Applying manifest
serviceaccount/coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
clusterrole.rbac.authorization.k8s.io/coredns created
clusterrolebinding.rbac.authorization.k8s.io/coredns created
Restarting kubelet
DNS is enabled

(microk8s) user@kris-workstation:~/PycharmProjects/microk8s$ sudo microk8s.enable dashboard
Enabling Kubernetes Dashboard
Enabling Metrics-Server
serviceaccount/metrics-server created
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader created
clusterrole.rbac.authorization.k8s.io/system:metrics-server created
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader created
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator created
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server created
service/metrics-server created
deployment.apps/metrics-server created
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io created
clusterrolebinding.rbac.authorization.k8s.io/microk8s-admin created
Metrics-Server is enabled
Applying manifest
serviceaccount/kubernetes-dashboard created
service/kubernetes-dashboard created
secret/kubernetes-dashboard-certs created
secret/kubernetes-dashboard-csrf created
secret/kubernetes-dashboard-key-holder created
configmap/kubernetes-dashboard-settings created
role.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
deployment.apps/kubernetes-dashboard created
service/dashboard-metrics-scraper created
deployment.apps/dashboard-metrics-scraper created

If RBAC is not enabled access the dashboard using the default token retrieved with:

token=$(microk8s kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s kubectl -n kube-system describe secret $token

In an RBAC enabled setup (microk8s enable RBAC) you need to create a user with restricted
permissions as shown in:
https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

(microk8s) user@kris-workstation:~/PycharmProjects/microk8s$ sudo microk8s.enable dns dashboard
Addon dns is already enabled.
Enabling Kubernetes Dashboard
Enabling Metrics-Server
serviceaccount/metrics-server unchanged
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/system:metrics-server unchanged
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader unchanged
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator unchanged
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server unchanged
service/metrics-server unchanged
deployment.apps/metrics-server configured
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io unchanged
clusterrolebinding.rbac.authorization.k8s.io/microk8s-admin unchanged
Metrics-Server is enabled
Applying manifest
serviceaccount/kubernetes-dashboard unchanged
service/kubernetes-dashboard unchanged
secret/kubernetes-dashboard-certs unchanged
secret/kubernetes-dashboard-csrf unchanged
secret/kubernetes-dashboard-key-holder unchanged
configmap/kubernetes-dashboard-settings unchanged
role.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
deployment.apps/kubernetes-dashboard unchanged
service/dashboard-metrics-scraper unchanged
deployment.apps/dashboard-metrics-scraper unchanged

If RBAC is not enabled access the dashboard using the default token retrieved with:

token=$(microk8s kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s kubectl -n kube-system describe secret $token

In an RBAC enabled setup (microk8s enable RBAC) you need to create a user with restricted
permissions as shown in:
https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

(microk8s) user@kris-workstation:~/PycharmProjects/microk8s$ sudo microk8s.kubectl get all -A
NAMESPACE     NAME                                          READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-64c6478b6c-n4qnp                  1/1     Running   0          2m41s
ingress       pod/nginx-ingress-microk8s-controller-jcf98   1/1     Running   0          3m37s
kube-system   pod/calico-node-z4tdw                         1/1     Running   0          4m2s
kube-system   pod/calico-kube-controllers-d8bc5d7f4-qv46z   1/1     Running   0          4m2s

NAMESPACE     NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes                  ClusterIP   10.152.183.1     <none>        443/TCP                  4m10s
kube-system   service/kube-dns                    ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   2m41s
kube-system   service/metrics-server              ClusterIP   10.152.183.37    <none>        443/TCP                  2m
kube-system   service/kubernetes-dashboard        ClusterIP   10.152.183.143   <none>        443/TCP                  117s
kube-system   service/dashboard-metrics-scraper   ClusterIP   10.152.183.194   <none>        8000/TCP                 117s

NAMESPACE     NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/calico-node                         1         1         1       1            1           kubernetes.io/os=linux   4m9s
ingress       daemonset.apps/nginx-ingress-microk8s-controller   1         1         1       1            1           <none>                   3m37s

NAMESPACE     NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/calico-kube-controllers     1/1     1            1           4m9s
kube-system   deployment.apps/coredns                     0/1     1            0           2m41s
kube-system   deployment.apps/metrics-server              0/1     0            0           2m
kube-system   deployment.apps/kubernetes-dashboard        0/1     0            0           117s
kube-system   deployment.apps/dashboard-metrics-scraper   0/1     0            0           117s

NAMESPACE     NAME                                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/calico-kube-controllers-6966456d6b   0         0         0       4m3s
kube-system   replicaset.apps/calico-kube-controllers-d8bc5d7f4    1         1         1       4m2s
kube-system   replicaset.apps/coredns-64c6478b6c                   1         1         0       2m41s
```

**Comment by krisstern** [comment]
Hi @knkski and @ktsakalozos Would appreciate it if a review can be made soon

**Comment by ktsakalozos** [comment]
Hi @krisstern, thank you for this PR. I think you missed the part where the addons are enabled of disabled [1]. We have to spot the right enable/disable script (including the extension) to call it.

[1] https://github.com/ubuntu/microk8s/blob/master/scripts/wrappers/common/utils.py#L243

**Comment by krisstern** [comment]
Thanks @ktsakalozos for the feedback! I will fix this last bit as soon as possible.

**Comment by krisstern** [comment]
I have just made the changes as suggested. If there is anything else to do to complete the PR please let me know! Appreciate it.

**Comment by ktsakalozos** [comment]
Hi @krisstern it does not seem to work for me. How did you test this work?

**Comment by krisstern** [comment]
Sorry, let me run the tests again like before in https://github.com/ubuntu/microk8s/pull/2795#issuecomment-993273706

**Comment by krisstern** [comment]
Hi, I just realised this PR may not be needed as kubeflow is slated to be removed in PR #2869.

**Pull request closed without merging**
