### PR TITLE
Including juju binary in snap instead of downloading it

### PR DESCRIPTION
**Pull request by knkski**
Downloading it with `microk8s.enable juju` leads to lots of networking issues with restrictive firewalls/proxies/etc.

Fixes issues such as #975

### CODE REVIEW

**Comment by balchua** [comment]
This will make microk8s binary huge.

**Comment by knkski** [comment]
@balchua: The juju binary that gets included in this PR is only ~14MB, and the snap is already 222MB. It's not nothing, but wouldn't increase the size considerably.

**Comment by balchua** [comment]
I see i thought juju tarball carries 116MB, atleast thats what is shown when i curl it.

**Comment by knkski** [comment]
The tarball we were downloading was that big, yeah, but there's a minified version that we're also switching to in this PR (the `centos7` vs `k8s` tarball)

**Comment by balchua** [comment]
Oh i see. Cool.

**Comment by ktsakalozos** [comment]
LGTM +1 thank you @knkski

**Pull request merged**
