### PR TITLE
Knative version update

### PR DESCRIPTION
**Pull request by saikiran2603**
### Thank you for making MicroK8s better

Updating knative version from 0.21 to 0.24. Tested the version and it seems to be working fine  

*Also verify you have:*
* [X] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [X] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you @saikiran2603, can you please make sure you have signed the CLA with the email account used in this PR?

**Comment by saikiran2603** [comment]
> Thank you @saikiran2603, can you please make sure you have signed the CLA with the email account used in this PR?

I think  i missed the launchpad ID, filled it again with correct launchpad ID

**Review by ktsakalozos — APPROVED** [review]
LGTM +1 thank you @saikiran2603

**Comment by ktsakalozos** [comment]
Thank you for your work @saikiran2603

**Pull request merged**
