### PR TITLE
Fix #719 - support for armhf and remote builds

### LINKED ISSUE #719: Microk8s on armhf architecture
Hi all, 

The armhf binary is missing and not available right now, which means that some users cannot install microk8s on Ubuntu. For example, if you use the armhf image for Raspberry Pi, you cannot install microk8s: 

> ubuntu@battlecruiser:~$ sudo snap install microk8s --classic
> error: snap "microk8s" is not available on stable for this architecture (armhf)
>        but exists on other architectures (amd64, arm64, ppc64el).

It would be really good if we could also get the build compiled for this architecture and make officially available. 

Cheers,

- Calvin

### PR DESCRIPTION
**Pull request by angelnu**

### CODE REVIEW

**Comment by angelnu** [comment]
tested with KUBE_VERSION=v.1.20.0 and it built sucesfully

**Comment by ktsakalozos** [comment]
Thank you for this PR @angelnu 

Note that it will take us a bit more time to go through it given there is an extra overhead in supporting a new architecture (hardware, CI, testing, things you do not see etc).

**Comment by ktsakalozos** [comment]
It might worth splitting the remote-builds patch in a separate PR.

**Comment by angelnu** [comment]
Yes, I can do the split.

I also noticed as I am doing my test that the commands to enable the addons are already not working correctly - most of them affect all nodes in the cluster so the relevant aspect before enabling is if the cluster contains only compatible architectures. Example: multus need to be enabled on x86 but it then works on arm/arm64.

**Comment by angelnu** [comment]
I will re-submit with just the armrf part now that the remote build got merged

**Pull request closed without merging**
