### PR TITLE
Adding repo link for Akri (MSFT) on MicroK8s

### PR DESCRIPTION
**Pull request by didier-durand**
Hi there,
as per title
Didier

### CODE REVIEW

**Review by balchua — COMMENTED** [review]
@didier-durand the link doesn't seem to be pointing to akri.  Shouldn't it be https://github.com/didier-durand/microk8s-akri

**Comment by didier-durand** [comment]
@balchua : Sorry, my bad! I didn't fully fix my cut & paste.... Do you want me to fix or do you prefer to do it?

**Comment by didier-durand** [comment]
Just fixed the link. Thanks for your careful check!

**Comment by didier-durand** [comment]
@balchua &  @ktsakalozos : thanks! Didier

**Pull request merged**
