### PR TITLE
Handle non-unified cgroups

### PR DESCRIPTION
**Pull request by ktsakalozos**
Fixes: https://github.com/ubuntu/microk8s/issues/519

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Merging to get some feedback.

**Comment by mcfedr** [comment]
how can one install this version and try it out?

**Comment by ktsakalozos** [comment]
> how can one install this version and try it out?

It is on the edge channel:
```
sudo snap install microk8s --classic --edge
```

**Comment by mcfedr** [comment]
got it, working for me now.

**Pull request merged**
