### PR TITLE
Revert to containerd 1.2.5 until we get gpu to work on 1.3.0

### PR DESCRIPTION
**Pull request by ktsakalozos**

### CODE REVIEW

**Comment by ktsakalozos** [comment]
I am sorry @balchua I have to revert the 1.3.0 transition. We accidentally broke the gpu support, see https://github.com/ubuntu/microk8s/issues/448 .

**Comment by balchua** [comment]
Oh shoot!! Im sorry.

**Comment by ktsakalozos** [comment]
> Oh shoot!! Im sorry.

No worries, I should have tested it better

**Comment by balchua** [comment]
Not too familiar with gpis, I was checking about this a little bit, according to this issue https://github.com/NVIDIA/k8s-device-plugin/issues/107
There is a need to change the runtime to use nvidia-container-runtime.

**Comment by ktsakalozos** [comment]
> Maybe in the new containerd, we dont have to change the runtime.

Yes, it might be something as simple as that. Unfortunately at the moment I do not have enough time to dig into that.

**Pull request merged**
