### PR TITLE
Update MetalLB to v0.9.3 and add support for CIDR notation

### PR DESCRIPTION
**Pull request by balchua**
This PR add CIDR support when specifying IP addresses.  Also upgrades metallb v0.9.3.

### CODE REVIEW

**Comment by balchua** [comment]
Fixes: #1431

**Comment by sstubbs** [comment]
Any idea when this can be merged?

**Comment by ktsakalozos** [comment]
The plan is to review this PR next week. It would speed things up if some
got the snap build artefact of the GitHub action and gave it a test-drive.
Thank you.

**Comment by sstubbs** [comment]
OK thank you. I will try and test this.

**Pull request merged**
