### PR TITLE
Upgrade cilium to 1.10

### PR DESCRIPTION
**Pull request by ktsakalozos**
Upgrade Cilium to 1.10, needed for v1.22 release.

### CODE REVIEW

**Review by joedborg — APPROVED** [review]
LGTM

**Review by balchua — APPROVED** [review]
Lgtm 👍

**Comment by xmulligan** [comment]
@ktsakalozos would you mind adding Microk8s to the Cilium adopters list? https://github.com/cilium/cilium/blob/master/USERS.md

We need this for when we apply to graduate at the CNCF

**Comment by ktsakalozos** [comment]
@xmulligan there is already Canonical and MicroK8s there.

Best of luck with the graduation!

**Comment by xmulligan** [comment]
Sorry missed it there under Canonical 😅 Thanks for already adding it 😄

**Pull request merged**
