### PR TITLE
Add OpenFaaS addon

### PR DESCRIPTION
**Pull request by LucasRoesler**
Create addon that installs openfaas using helm3. The user can toggle if the installation should enable basic auth and if it should install the operator mode instead of the standard faas-netes controller.  All other settings can be controlled via an external values files that can be passed as a flag.

### CODE REVIEW

**Comment by LucasRoesler** [comment]
The build error is related to the dqlite patch not being applicable to the latest k8s release: v1.20.1 I was able to test this locally by overriding the version to v1.20.0

**Review by ktsakalozos — APPROVED** [review]
LGTM +1 thank you @LucasRoesler . Nice work.

**Comment by ktsakalozos** [comment]
Sorry for the late review. The addon will be available on the latest/edge channel within the day and will land on the stable branch with the 1.21 release.

**Comment by LucasRoesler** [comment]
@ktsakalozos no worries, I understand how things go. Thanks for looking and merging :muscle: very exciting!

**Comment by ktsakalozos** [comment]
@LucasRoesler just added a placeholder for openfaas on our docs [1]. Any suggestions on what do you want to be there.

@evilnick this is a new addon that will be available with the 1.21 release.

[1] https://discuss.kubernetes.io/t/addon-openfaas/14981

**Comment by LucasRoesler** [comment]
@ktsakalozos i have a snippet we can use for those docs, but Alex also pointed out something to me that I got the auth flag backwards, is it still possible to patch it before the release? e.g. 

```diff
diff --git microk8s-resources/actions/enable.openfaas.sh microk8s-resources/actions/enable.openfaas.sh
index 5f96670..9363591 100755
--- microk8s-resources/actions/enable.openfaas.sh
+++ microk8s-resources/actions/enable.openfaas.sh
@@ -16,7 +16,7 @@ echo ""
 echo "Enabling OpenFaaS"

 OPERATOR=false
-AUTH=false
+AUTH=true
 VALUES=""

 for i in "$@"
@@ -26,8 +26,8 @@ case $i in
     OPERATOR=true
     shift # past argument
     ;;
-    --auth)
-    AUTH=true
+    --no-auth)
+    AUTH=false
     shift # past argument
     ;;
     -f=*|--values=*)
@@ -77,4 +77,3 @@ fi

 # print a final help message
 echo "OpenFaaS has been installed"
```

Install will look like 
```sh
microk8s enable openfaas --auth
Addon dns is already enabled.
Addon helm3 is already enabled.
Enabling OpenFaaS
Operator: false
Basic Auth enabled: true
"openfaas" has been added to your repositories
Release "openfaas" does not exist. Installing it now.
NAME: openfaas
LAST DEPLOYED: Sun Feb 28 13:05:19 2021
NAMESPACE: openfaas
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To verify that openfaas has started, run:

  kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas"
To retrieve the admin password, run:

  echo $(kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode)
OpenFaaS has been installed
```
providing the user the command to retrieve the password.


If so, then I can open a new PR and the related docs would look like:

> Homepage: https://www.openfaas.com/
> Docs: https://docs.openfaas.com/
> From MicroK8s version: 1.21+
> Supported arch: amd64, arm64
> [OpenFaaS](https://docs.openfaas.com/), the popular serverless framework, can be enabled with:
> ```
> microk8s enable openfaas
> ```
> Disable basic auth using the `--no-auth` flag. 
> If you would like to use the OpenFaaS Operator mode, use `--operator`.
> 
> Further customize the installation by passing a values file using
> ```
> microk8s enable openfaas -f values.yaml
> ```
> The possible values are documented [here](https://github.com/openfaas/faas-netes/tree/master/chart/openfaas#configuration)
>

**Comment by ktsakalozos** [comment]
Sure @LucasRoesler, just submit  a PR with the fix.

**Comment by LucasRoesler** [comment]
@ktsakalozos the new PR is here https://github.com/ubuntu/microk8s/pull/2066

**Pull request merged**
