### PR TITLE
Add Juju disable script

### PR DESCRIPTION
**Pull request by knkski**
Otherwise, if someone attempts to change the Juju version, they'll be stuck with the old version unexpectedly.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
I am not sure about this PR @knkski. What problem do we solve? Why don't we implement the `microk8s.disable juju` command so as to allow users to remove and install juju at will?

**Comment by ktsakalozos** [comment]
> attempts to change the Juju version, they'll be stuck with the old version unexpectedly

The user should not expect to change the JUJU_VERSION and have microk8s follow. In the same way we ship specific/blessed versions of all other components. Are you sure your kubeflow bundle will work with juju 2.9.0?

**Comment by ktsakalozos** [comment]
@knkski what if we implement the `microk8s.disable juju` command and when we do a `microk8s.enable kubeflow` we call the disabling of juju?

**Comment by knkski** [comment]
@ktsakalozos, @johnsca: Thanks, updated the PR to disable Juju when Kubeflow gets disabled.

**Comment by ktsakalozos** [comment]
@johnsca thank you for your input on this. Keeping juju uptodate is going to be a tricky and we need to find a way to do this properly.

**Pull request merged**
