### PR TITLE
Bump juju version

### PR DESCRIPTION
**Pull request by joedborg**
Bump to juju 2.9

### CODE REVIEW

**Comment by joedborg** [comment]
Manually tested and seems fine.

**Comment by DomFleischmann** [comment]
The kubeflow bundle revision that is currently on master breaks with juju 2.9. This is not happening with the latest bundle for Kubeflow 1.3. Therefore we probably should wait with merging this until Kubeflow 1.13 works with microk8s 1.21.

**Comment by ktsakalozos** [comment]
I am closing this as this upgrade has be addressed in the upgrade of KF.

**Comment by DomFleischmann** [comment]
We didn't update the juju version in the KF upgrade so this is still relevant.

**Comment by joedborg** [comment]
Tested and working with KF:

```
ubuntu@ip-172-31-30-193:~$ microk8s enable kubeflow
Enabling dns...
Enabling storage...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for other addons to finish initializing...
Addon setup complete. Checking connectivity...
Bootstrapping...
Bootstrap complete.
Successfully bootstrapped, deploying...
Kubeflow deployed.
Waiting for operator pods to become ready.
Waited 0s for operator pods to come up, 27 remaining.
Waited 15s for operator pods to come up, 27 remaining.
Waited 30s for operator pods to come up, 26 remaining.
Waited 45s for operator pods to come up, 26 remaining.
Waited 60s for operator pods to come up, 26 remaining.
Waited 75s for operator pods to come up, 25 remaining.
Waited 90s for operator pods to come up, 24 remaining.
Waited 105s for operator pods to come up, 24 remaining.
Waited 120s for operator pods to come up, 22 remaining.
Waited 135s for operator pods to come up, 20 remaining.
Waited 150s for operator pods to come up, 18 remaining.
Waited 165s for operator pods to come up, 14 remaining.
Waited 180s for operator pods to come up, 14 remaining.
Waited 195s for operator pods to come up, 14 remaining.
Waited 210s for operator pods to come up, 12 remaining.
Waited 225s for operator pods to come up, 11 remaining.
Waited 240s for operator pods to come up, 9 remaining.
Waited 255s for operator pods to come up, 9 remaining.
Waited 270s for operator pods to come up, 6 remaining.
Waited 285s for operator pods to come up, 4 remaining.
Waited 300s for operator pods to come up, 5 remaining.
Waited 315s for operator pods to come up, 5 remaining.
Waited 330s for operator pods to come up, 5 remaining.
Waited 345s for operator pods to come up, 3 remaining.
Waited 360s for operator pods to come up, 2 remaining.
Waited 375s for operator pods to come up, 2 remaining.
Waited 390s for operator pods to come up, 1 remaining.
Waited 405s for operator pods to come up, 1 remaining.
Waited 420s for operator pods to come up, 1 remaining.
Operator pods ready.
Congratulations, Kubeflow is now available.

The dashboard is available at http://10.64.140.43.nip.io

    Username: admin
    Password: 3WCV1448NZYB8I4GYO3P82F5HWVRIF

To see these values again, run:

    microk8s juju config dex-auth static-username
    microk8s juju config dex-auth static-password



To tear down Kubeflow and associated infrastructure, run:

    microk8s disable kubeflow
    ```

**Comment by DomFleischmann** [comment]
I think this can be merged

**Pull request merged**
