### PR TITLE
Disabling linkerd on 1.16 untill the addon is fixed

### PR DESCRIPTION
**Pull request by ktsakalozos**

### CODE REVIEW

**Comment by ktsakalozos** [comment]
@balchua I am going to merge this so the release is unblocked. As soon as we get  https://github.com/ubuntu/microk8s/pull/619 we should turn linkerd addon back on.

**Comment by ktsakalozos** [comment]
Thanks @johnsca

**Comment by balchua** [comment]
Sure thing. You are releasing 1.16 today?

**Comment by ktsakalozos** [comment]
@balchua the plan is to get 1.16 in 1.16/latest,1.16/candidate, 1.16/beta,1.16/edge, latest/candidate, latest/beta, latest/edge asap (today), and do the release to latest stable next week.

In the mean time I am trying to get linkerd running, with not much success.

**Comment by balchua** [comment]
Same symptoms as you mentioned before?

**Comment by ktsakalozos** [comment]
Worse :) . Some pods are crashlooping. You got it working by disabling some of the apiserver args? Remember which ones?

**Comment by balchua** [comment]
you're right.  After I sync the changes today, there are 3 pods crashlooping.
Even if I removed the `--requestheader-allowed-names` option in the kube-apiserver.  I didn't see this the day before.

**Comment by balchua** [comment]
@ktsakalosoz Kube 1.16 removed some deprecated apis which linkerd 2.5.0 and below still uses.  It's been addressed, but not released in stable version yet.  I think this is also the case for knative.  
But it can be temporarily enabled using the apiserver option `--runtime-config` flag.

**Comment by wmorgan** [comment]
Almost ready for 2.6, which will work on 1.16. Stay tuned. cc @grampelberg

**Pull request merged**
