### PR TITLE
Fix gpu support on containerd 1.3+

### PR DESCRIPTION
**Pull request by balchua**
Hi,

I've used the `version 2` configuration of containerd.  `version 1` config still works, and is currently the default.  I just thought that we will anyway eventually get there.

notable changes will be the introduction of "uri"

For example the cri registry mirror config:
Previously
```
        [plugins.cri.registry.mirrors."localhost:32000"]
          endpoint = ["http://localhost:32000"]
```
Now it will include the "uri"

```
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:32000"]
        endpoint = ["http://localhost:32000"]        
```

The configuration of the `default` runtime is also different.
It is no longer configured at the linux plugin.

Previously:
```
  [plugins.linux]
    shim = "containerd-shim"
    runtime = "${RUNTIME}"
    runtime_root = ""
    no_shim = false
    shim_debug = true
```

Now:
```
  [plugins."io.containerd.grpc.v1.cri".containerd]
   snapshotter = "overlayfs"
   no_pivot = false
   default_runtime_name = "${RUNTIME}"
```

This is followed by the runtime configurations.  `runc` configurations are all defaults.

```
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
      # runtime_type is the runtime type to use in containerd e.g. io.containerd.runtime.v1.linux
      runtime_type = "io.containerd.runc.v1"

    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia-container-runtime]
      # runtime_type is the runtime type to use in containerd e.g. io.containerd.runtime.v1.linux
      runtime_type = "io.containerd.runc.v1"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia-container-runtime.options]
        BinaryName = "nvidia-container-runtime"
```
I tried to still show the previous settings even though they are default values.

It works on GPU powered machines.

My main concern, is when users modified the `containerd-template.toml`, they will have to be notified of the changes.

### CODE REVIEW

**Comment by balchua** [comment]
More information on version 2 cri configuration: https://github.com/containerd/cri/blob/release/1.3/docs/config.md

**Comment by balchua** [comment]
Should address https://github.com/ubuntu/microk8s/issues/448

**Comment by ktsakalozos** [comment]
Thank you for your work on this PR @balchua.

Indeed if people have modified their `containerd-template.toml` we will run into trouble. We would better time this PR with one of the upstream releases and provide some migration automation in our configure script (at least for any registries and the runtime). I am out this week and next week 1.17 release is planned. We would better wait for the 1.18 to do this transition. What do you think?

**Comment by balchua** [comment]
Pushing it to 1.18 is fine with me.  Either way we need to have an automated migration process as you said.  Need more discussion.  Can u add labels to prs that needs more discussions?

**Comment by balchua** [comment]
There is another feature in containerd that allows one to import config.  I will try that one too.  The idea is to have user's custom config can live outside the template.

Something like this 
```
imports = ["/var/snap/microk8s/current/containerd/custom/*.toml"]
```

**Comment by mbrancato** [comment]
Does this need a rebase / merge fix to get merged into the 1.18 branch?

**Comment by rtiwary-dev** [comment]
containerd 1.3.2 adds support for insecure-skip-verify for insecure registries. Can that version be included on the next microk8s release? https://github.com/containerd/containerd/issues/3847

**Comment by balchua** [comment]
@rtiwary-dev i will try to update the pr with the latest containerd.

**Comment by ktsakalozos** [comment]
I moved your work in https://github.com/ubuntu/microk8s/pull/1302 @balchua .

Thank you and tell me what you think on the new PR.

**Pull request closed without merging**
