### PR TITLE
Swap out travis for github actions

### PR DESCRIPTION
**Pull request by joedborg**
Draft PR to see if this works.

### CODE REVIEW

**Comment by balchua** [comment]
This is nice 👍 github actions also supports windows and mac runners.

**Comment by joedborg** [comment]
> This is nice +1 github actions also supports windows and mac runners.

Yeah, it would be nice to not have to split this between travis and appveyor.

**Comment by balchua** [comment]
Last time i tried launching microk8s using github actions and perform some tests, i have to chown the root path `/` to `root:root`.  I still have it in one of my projects in github.  But i haven't run it for quite sometime, it may have changed.

**Comment by ktsakalozos** [comment]
@joedborg is this still a draft? What do you think if we run travis and gh actions at the same time for some period?

**Comment by ktsakalozos** [comment]
Closing this in favor of https://github.com/ubuntu/microk8s/pull/1376

**Pull request closed without merging**
