### PR TITLE
Make `microk8s.status` addons more readable

### PR DESCRIPTION
**Pull request by balchua**
With the list of addons growing, it is becoming difficult to show which ones are enabled or disabled.
This PR now groups the enabled and disabled addons (added some colors).
Example:
Non yaml output.
```
microk8s.status 
microk8s is running
addons:
enabled:
  dns
  rbac

disabled:
  cilium
  dashboard
  fluentd
  gpu
  helm
  ingress
  istio
  jaeger
  juju
  knative
  kubeflow
  linkerd
  metallb
  metrics-server
  prometheus
  registry
  storage
```

Yaml output:
```
microk8s:
  running: true
addons:
  enabled:
  - rbac
  - dns
  disabled:
  - knative
  - jaeger
  - juju
  - fluentd
  - gpu
  - cilium
  - storage
  - helm
  - registry
  - metallb
  - ingress
  - metrics-server
  - linkerd
  - prometheus
  - istio
  - dashboard
  - kubeflow
```

### CODE REVIEW

**Comment by balchua** [comment]
I am going to continue working on this.  Some few improvements and missing feature that i would like to address.

@ktsakalozos can i use the path `scripts/cluster` to keep some common utilities that i may have?  Or this path is solely for clustering feature?
Thanks.

**Comment by ktsakalozos** [comment]
> can i use the path `scripts/cluster`

Do you think a "scripts/common" would be better?

**Comment by balchua** [comment]
Yeah `scripts/common` is more appropriate.
Thanks

**Comment by balchua** [comment]
Worked the following:
- Support providing individual addon status.  Example: `microk8s.status --addon dns`, the output can be `enabled` or `disabled`.
- Make `microk8s.enable` and `microk8s.disable` idempotent.
- Separate the utilility python functions to `scripts/wrappers/common`. 
- `microk8s.enable --help`, shows this output.

```
$ microk8s.enable --help
Usage: microk8s.enable ADDON...
Enable one or more ADDON included with microk8s
Example: microk8s.enable dns storage
Available Addons:
  cilium               # Cilium CNI - https://cilium.readthedocs.io/en/stable/intro/
  dashboard            # Dashboard is a web-based Kubernetes user interface.
  dns                  # CoreDNS is a DNS server/forwarder, written in Go, that chains plugins.
  fluentd              # Log forwarder Fluentd with Elasticsearch
  gpu                  # NVIDIA GPU support
  helm                 # Helm 2: The package manager for Kubernetes
  helm3                # Helm 3: The package manager for Kubernetes
  ingress              # NGINX Ingress Controller for Kubernetes
  istio                # Service mesh that provides traffic management, policy enforcement, and telemetry collection.
  jaeger               # Jaeger Operator
  juju                 # Juju is an open source application modeling tool developed by Canonical Ltd.
  knative              # Knative offers scale-to-zero, autoscaling, in-cluster builds, and eventing framework on Kubernetes.
  kubeflow             # The Kubeflow project is dedicated to making deployments of machine learning (ML) workflows on Kubernetes
  linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks.
  metallb              # MetalLB is a load-balancer implementation for bare metal Kubernetes clusters, using standard routing protocols.
  metrics-server       # Metrics Server is a cluster-wide aggregator of resource usage data.
  prometheus           # Prometheus Operator -  https://github.com/coreos/prometheus-operator.git
  rbac                 # Kubernetes Role Based Access Control
  registry             # An implementation of the Docker Registry HTTP API V2 for use with docker 1.6+. - https://hub.docker.com/r/cdkbot/registry-amd64
  storage              # Hostpath provisioner CSI. - https://hub.docker.com/r/cdkbot/hostpath-provisioner-amd64
```

**Comment by balchua** [comment]
With the changes, this issue https://github.com/ubuntu/microk8s/issues/905 can be addressed.

**Comment by ktsakalozos** [comment]
@balchua I did a rebase and a few review changes so we get ready for 1.18 release. Thank you for this work.

**Comment by balchua** [comment]
Thank you!

**Comment by balchua** [comment]
@ktsakalozos did u leave some reviews?  I couldn't find them.

**Comment by ktsakalozos** [comment]
I fixed all the issues I found and did a force push because there were conflicts.

There is nothing specific to for you do do. Just review the new PR. Thanks.

**Comment by balchua** [comment]
Lgtm thanks.

**Comment by ktsakalozos** [comment]
Thank you @balchua

**Pull request merged**
