### PR TITLE
Do not ship openfaas on arm64

### PR DESCRIPTION
**Pull request by ktsakalozos**
The manifests produced by the openfaas addon are amd64 specific. They have:
```
      nodeSelector:
        beta.kubernetes.io/arch: amd64
```

### CODE REVIEW

**Comment by ktsakalozos** [comment]
@LucasRoesler maybe we can add ARM64 support at a later stage.

**Review by joedborg — APPROVED** [review]
LGTM

**Review by kwmonroe — APPROVED** [review]

**Comment by LucasRoesler** [comment]
> @LucasRoesler maybe we can add ARM64 support at a later stage.

You are right. I made a mistake because we had moved all of the images to multi-arch builds and there was discussion that the helm chart should work. OpenFaaS can work on ARM, but there are just a few tweaks needed to the install flow. I will followup with the needed tweaks.

**Comment by LucasRoesler** [comment]
@ktsakalozos when is the next release for microk8s? We just removed the node selector this weekend and I am waiting for a new helm chart release. Once that is released, it will work on ARM out of the box and we could revert this PR.

**Comment by ktsakalozos** [comment]
> when is the next release for microk8s?

Next release v1.21 is in a couple of days (8th of April). The v1.22 should be in about 4 months.

**Comment by alexellis** [comment]
We fixed this yesterday, so for the next cycle of MicroK8s, this can be enabled again on ARM64.

**Pull request merged**
