### PR TITLE
Add pytest based nodetest

### PR DESCRIPTION
**Pull request by chris-sanders**
This brings install and upgrade testing up to parity with the bash based
version. Reorganize the testnode code into a module instead of
one large file. Finally fixed linting as well.

### CODE REVIEW

**Comment by joedborg** [comment]
A few points for 2021 us:

* These don't run on EC2 probably due to a weird bug with LXD.
* Timeouts seem a bit low, e.g. my laptop can't bring up DNS in time.
* Docker is not running inside the LXD container so tests fail on docker pull.

**Comment by chris-sanders** [comment]
I've added a global test coefficient. I have no idea what was going on with that EC2 instance, but I suspect the current bash scripts fail in the same way since spin up LXD containers with this same profile and install the same snaps.

I don't follow the docker issue though, I don't experience that. I think you might be hitting a snap in lxd on zfs issue. If you can reproduce but I don't hit that particular issue.

I do wonder if some of the timeouts should be increased for individual things that are being cut a little to close. I was setting these based on passing on my laptop but it was just a starting point. We should play with global vs individual tests to land them wherever seems the most appropriate.

**Comment by chris-sanders** [comment]
With the last push all tests are passing again for me, try the environment variable to adjust timeouts and see if this runs for you now @joedborg

**Comment by joedborg** [comment]
@chris-sanders https://github.com/ubuntu/microk8s/commit/466df0a2f7d9ab345f8818009632d395197842f0 needs merging into this PR

**Comment by chris-sanders** [comment]
@joedborg added

**Review by joedborg — APPROVED** [review]
LGTM!

**Pull request merged**
