### PR TITLE
Feature/modifiable csr

### PR DESCRIPTION
**Pull request by balchua**
In relation to the issue https://github.com/ubuntu/microk8s/issues/421 this PR makes a copy of csr.conf.template to `$SNAP_DATA/certs`, so users can add additional IPs.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you for the PR @balchua +1

**Comment by pixelshaded** [comment]
Using 1.14/edge snap, I cannot get my edits to the template to work. Once you edit the template, how do you get microk8s to generate a new certificate from the template? I've stopped, started, and even reset the cluster with no luck. I always get the same list of hosts from the certificate error.

**Comment by balchua** [comment]
@pixelshaded you're right, i couldn't find anywhere that regenerates the csr other than when the apiserver-kicker determines there is a change in the ip.  
Is the ip you are adding to the template not showing up when you do a `hostname -I`?

**Comment by balchua** [comment]
@pixelshaded i may have found something, do you see a file `external_ip.txt` in `/var/snap/microk8s/current`?  If yes can you also add your ip address into that? And do a `microk8s.stop` then start? I think this may trigger the apiserver-kicker to recreate the server certs based on the `csr.conf.template`.

**Comment by ktsakalozos** [comment]
@pixelshaded @balchua indeed this fix/feature needs a bit more thinking. The user experience is not good. 

@pixelshaded here is another way to update the csr file.
 - update `/var/snap/microk8s/current/certs/csr.conf.template` based on your needs
 - `rm  /var/snap/microk8s/current/certs/csr.conf`
 - `sudo snap set microk8s csr-refresh=true`

**Comment by pixelshaded** [comment]
@balchua I'm not sure the external_ip.txt will work for my use case because I want to add a domain and not an IP. @ktsakalozos your suggestion worked for updating the file.

**Comment by balchua** [comment]
@pixelshaded @ksakalozos thanks! Yeah we need to think about this a little bit more than just copying the template to the SNAP_DATA.

**Comment by ktsakalozos** [comment]
@balchua what if we kept a copy of the template currently used under `$SNAP_COMMON/var/run`. When MicroK8s starts we detect if there are any changes on the template since last boot.

**Comment by balchua** [comment]
@ktsakalozos the template in `$SNAP_COMMON/var/run` is the last used template and using this file and compare it with `$SNAP_DATA/certs/csr.conf.template`?

That can be a way, but why not render the `csr.conf.template` and compare that with `csr.conf`.  Unless there is something else im missing.  

Either way ,about the comparison, do we compare the data or a simple checksum / diff comparison will suffice?

**Comment by ktsakalozos** [comment]
I believe you are right we could split the fuction https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/common/utils.sh#L145 in a `render_server_csr` and `produce_server_cert` so we could compare the current `csr.conf` to a rendered candidate.

Now that I am looking at the code it makes sense to have the apiservice kicker (https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/apiservice-kicker)  detect changes in the same way it already does for the IPs. So the if statement in https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/apiservice-kicker#L29 may look like "if (rendered.csr.conf differs from ${SNAP_DATA}/certs/csr.conf) then re-create certs". This should actually detect both IP and user changes, so we should be fine.

A checksum or diff should be enough, we will need to add the utility in the `snapcraft.yaml` to use it.

**Comment by balchua** [comment]
Let me create an issue to keep track of this.

**Pull request merged**
