### PR TITLE
Nginx Ingress Changes and Linkerd Upgrade

### PR DESCRIPTION
**Pull request by balchua**
Changes on ingress:

- Upgrade to nginx 0.25.1, some security fixes.  Including arm64.
- Remove default backend controller.
- Move to ingress namespace.

Linkerd upgrade to v2.5.0

Need help in testing arm64.

### CODE REVIEW

**Comment by balchua** [comment]
Will address this issue https://github.com/ubuntu/microk8s/issues/499.

**Comment by balchua** [comment]
I need to figure out why linkerd validation is not finishing.

**Comment by balchua** [comment]
I couldn't figure out why tests are failing.  I've skipped linkerd validation and yet it still timing out.

**Comment by balchua** [comment]
The build is timing out when the `patch-kube-proxy.sh` is restarting the daemon.
`systemctl restart snap.microk8s.daemon-proxy`

**Comment by ktsakalozos** [comment]
The upgrade test we run in travis https://github.com/ubuntu/microk8s/blob/master/.travis.yml#L20
```
sudo UPGRADE_MICROK8S_FROM=edge UPGRADE_MICROK8S_TO=`pwd`/`ls microk8s*.snap` pytest -s ./tests/test-upgrade.py
```
will first snap install microk8s from edge, enable the addons run all the validators, upgrade to the local build of the snap and then run the same validators. In this way we make sure the validators run correctly before and after the upgrade. This is how we make sure we do not break deployments.

With this PR we move the ingress in its own namespaces ("ingress"). The ingress validator (https://github.com/ubuntu/microk8s/blob/master/tests/validators.py#L80) needs to be passing in both the old snap and the new one. The problem is that the validator waits for the ingress controller in the "ingress" namespaces so it is waiting forever since in the edge snap the ingress controller is on the default namespace.

**Comment by balchua** [comment]
thank you!  The logs didnt print that its enabling the addons from edge. 😁. Now i got it.

**Comment by balchua** [comment]
Finally got it going. Thanks for the help.

**Comment by ktsakalozos** [comment]
@balchua sorry for the delay in this review, I had to finish with the clustering work.

When deleting `emojivoto` the namespace stays terminating for ever causing the linkerd validator to fail/get stuck. Any idea what may be causing this?

**Comment by ktsakalozos** [comment]
When linkerd is enabled, I see this message on the apiserver logs (`journalctl -u snap.microk8s.daemon-apiserver -f`):
```
 Sep 13 08:57:24 ip-172-31-20-243 microk8s.daemon-apiserver[9008]: E0913 08:57:24.955771    9008 available_controller.go:409] v1alpha1.tap.linkerd.io failed with: failing or missing response from https://10.152.183.133:443/apis/tap.linkerd.io/v1alpha1: bad status from https://10.152.183.133:443/apis/tap.linkerd.io/v1alpha1: 400
```

**Comment by balchua** [comment]
No worries for the delay.  
About the hanging issue, I didn't see on my end.  Regarding the api server logs i will have to check.  Thanks for the review.

**Comment by balchua** [comment]
@ktsakalozos when those logs shows up, is it also the time when emojivoto namespace hangs on delete? Or it just shows up as long as linkerd is enabled.  Thanks

**Comment by ktsakalozos** [comment]
The error in the logs shows up as soon as the addon gets enabled.

**Comment by balchua** [comment]
I could not reproduce both the issues you are seeing.  But im going to clean up the `disable linkerd` to simply remove the control plane.  Apps injected with the linkerd proxy must manually remove the annotations manually.

**Comment by balchua** [comment]
Im going to ask the Linkerd folks in slack about the logs emitted by the api server.

**Comment by balchua** [comment]
I think those errors that you see could be transient.  Every pod inside the Linkerd control plane is also meshed with linkerd.  The tap controller will only be accessible once the linkerd  proxy sidecar is up and running.  Can you try `microk8s.linkerd check` to see if all are good?

**Comment by ktsakalozos** [comment]
@balchua could you rebase? Cannot think of anything else.

**Comment by balchua** [comment]
Im sorry what do you mean?

**Comment by ktsakalozos** [comment]
I still see this error, but you do not. So it could be that the branch you have does not have the latest patches that went into the master. Could you update your branch with the latest patches (normally with a `git rebase`)? I can't think of anything else.

**Comment by balchua** [comment]
Aaa ok got it. Thanks.

**Comment by balchua** [comment]
I am able to reproduce the error you are seeing.  Its strange.  I'm trying to get help from linkerd folks.

**Comment by ktsakalozos** [comment]
@balchua I suspect that for the namespaces stuck in the terminating state we should first clear resources in those namespaces (eg crds).

I am going to merge this PR https://github.com/ubuntu/microk8s/pull/646 so we get ready for v1.16 release. We might get some minor conflicts.

**Comment by balchua** [comment]
@ktsakalozos, thanks for the heads up.  Emojivoto doesn't have any crd, but yes i can try that one.

**Comment by balchua** [comment]
I tried linkerd 2.5.0 on 1.15 stable. It is working. The apiserver is not complaining about the tap pod.  Emojivoto is also deleted. it takes a bit of time though but it goes away.

**Comment by balchua** [comment]
@ktsakalozos I think i found the reason for the errors we are seeing in the apiserver logs.  When I removed this aggregation layer argument in the kube-apiserver `--requestheader-allowed-names=front-proxy-client` it started working.  My knowledge on the aggregation layer is low, may i ask if this argument is safe to remove?

**Comment by ktsakalozos** [comment]
You can remove it when linkerd is enabled and enable it in the disable script. 

Please use the skip https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/common/utils.sh#L110
and refresh https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/common/utils.sh#L69 config option arguments.

**Comment by ktsakalozos** [comment]
I am +1 to using `--runtime-config` flag while we wait.

**Pull request closed without merging**
