### PR TITLE
 if os using cgroup v2 then choose runc.v2

### LINKED ISSUE #2054: Confusing output when inspecting a cgroup2 enabled cluster
Using Ubuntu 20:10 on a Raspberry Pi4 (8Gb) with the latest 1.20.4 edge channel release (2064 at the time). _I.e. this configuration is using cgroups2 for the os._

I can schedule pods and all 5 nodes look ok.
```
ubuntu@k3s4:~$ sudo microk8s.kubectl get no -o wide                                                                                              
NAME   STATUS   ROLES    AGE     VERSION                     INTERNAL-IP      EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION     CONTAINER-RUNTIME  
k3s3   Ready    <none>   9h      v1.20.4-37+40f5d308636e9f   192.168.68.203   <none>        Ubuntu 20.10   5.8.0-1016-raspi   containerd://1.4.3 
k3s4   Ready    <none>   9h      v1.20.4-37+40f5d308636e9f   192.168.68.204   <none>        Ubuntu 20.10   5.8.0-1015-raspi   containerd://1.4.3 
k3s1   Ready    <none>   3h41m   v1.20.4-37+40f5d308636e9f   192.168.68.201   <none>        Ubuntu 20.10   5.8.0-1016-raspi   containerd://1.4.3 
k3s5   Ready    <none>   10h     v1.20.4-37+40f5d308636e9f   192.168.68.205   <none>        Ubuntu 20.10   5.8.0-1016-raspi   containerd://1.4.3 
k3s2   Ready    <none>   9h      v1.20.4-37+40f5d308636e9f   192.168.68.202   <none>        Ubuntu 20.10   5.8.0-1015-raspi   containerd://1.4.3 
```

however output of `microk8s.inspect` shows cgroups warning.

```
Inspecting kubeflow
  Inspect Kubeflow

 WARNING:  Port 16443 seems to be in use by another application.
# Warning: iptables-legacy tables present, use iptables-legacy to see them
WARNING:  The memory cgroup is not enabled.
The cluster may not be functioning properly. Please ensure cgroups are enabled
See for example: https://microk8s.io/docs/install-alternatives#heading--arm
```

The following output of `cat /boot/firmware/cmdline.txt`

`cgroup_enable=memory cgroup_memory=1 systemd.unified_cgroup_hierarchy=1 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc quiet splash`

the output of mount on one of the cgroup2 nodes contains this line
`cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)`
whereas on a cgroup v1 os

`cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)`

The check in [inspect.sh](https://github.com/ubuntu/microk8s/blob/12a24a86eecdc96b6b2e1c259a322170637e5ccd/scripts/inspect.sh#L186)
probably needs tweaking to cater for cgroups2

#2052

### PR DESCRIPTION
**Pull request by tbertenshaw**
Add better diagnosic output to show  the absence of cgroup. Or if cgroup1 or 2 are being used.  Fixes #2054

### CODE REVIEW

**Comment by tbertenshaw** [comment]
@ktsakalozos  added the ability to change the `containerd.toml` to  use `cgroupV2` if the `os` is currently running with `cgroupV2`.

I used the same test logic as in the inspect.sh `cgroup` test. I'm not sure if this is more correct than checking for if we are running with `systemd.unified_cgroup_hierarchy=0` or `systemd.unified_cgroup_hierarchy=1`

**Comment by tbertenshaw** [comment]
Is there anything i can do to improve this PR? I have build locally (pulling in master frequently) and it is working well for auto selecting runcV2.

**Comment by ktsakalozos** [comment]
Hi @tbertenshaw already looked at this PR, there is nothing wrong with it. We will target v1.22 for this to get some more testing on the v2 cgroups across as many distributions as we can.

**Comment by tbertenshaw** [comment]
@ktsakalozos cool.

**Comment by tbertenshaw** [comment]
just pulled master into my branch since 1.21.

Notice failing on CLA check. Is there something i am missing. I did notice a recent CLA check commit, i have signed the CLA.

**Comment by tbertenshaw** [comment]
closing and replacing with #2219

**Pull request closed without merging**
