### PR TITLE
First pass to build for Windows

### PR DESCRIPTION
**Pull request by joedborg**
`instance.launch_instance()` (L176) causes an exception after Microk8s has installed due to the `spec` argument being required.

Not sure why we'd want to launch at this stage; is it in case the VM has gone away?

### CODE REVIEW

**Comment by joedborg** [comment]
Have tested this build, on Windows and it fixes the issue.

**Comment by joedborg** [comment]
[MicroK8s Windows installer](https://trello.com/c/2VTGnwCa/1434-microk8s-windows-installer)

**Comment by joedborg** [comment]
@ktsakalozos This is ready to go into your branch.  It's now cleanly installing Multipass on Windows too.

Capture

**Comment by ktsakalozos** [comment]
Thank you @joedborg

**Pull request merged**
