### PR TITLE
Update containerd-template.toml

### PR DESCRIPTION
**Pull request by SamyCoenen**
Allow Microk8s to pull images from it's own private registry.
Especially useful for local development with tools like Skaffold.

Steps to enable:
```sh
microk8s.enable registry
microk8s.enable dns
microk8s.stop
microk8s.start
```

Fixes https://github.com/ubuntu/microk8s/issues/390

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you for this PR @SamyCoenen. Can you point me to a tutorial or a use case where this fix exercised? I am interested to know how Skaffold is taking these internal dns entries (eg registry.container-registry.svc) and exposes them to containerd running on the host.

**Comment by SamyCoenen** [comment]
@ktsakalozos I'm using it with a workflow that builds the images inside the cluster with Kaniko, deploys the new tags using Helm and syncs file changes to running containers. 
What you are referring to
>  I am interested to know how Skaffold is taking these internal dns entries (eg registry.container-registry.svc) and exposes them to containerd running on the host.

is an open issue, as the host doesn't need to have access to the registry: https://github.com/GoogleContainerTools/skaffold/issues/2217
I solved this by doing 2 things for now:
```sh
echo '127.0.0.1 registry.container-registry.svc.cluster.local' | sudo tee --append /etc/hosts
kubectl port-forward service/registry -n container-registry 5000:5000
```

an example Skaffold file might start with this

```yml
apiVersion: skaffold/v2beta1
kind: Config
build:
  cluster: {}
  insecureRegistries:
    - registry.container-registry.svc.cluster.local:5000
  artifacts:
    - image: registry.container-registry.svc.cluster.local:5000/my-image
```

**Comment by SamyCoenen** [comment]
The kubelet can pull the images because the dns addon updates it's configuration
https://github.com/ubuntu/microk8s/blob/395bc12671a12ca14e79f5a72d06765873068210/microk8s-resources/actions/enable.dns.sh#L23

This results in the following `kubelet` configuration file on my host at `/var/snap/microk8s/current/args/kubelet`

```sh
--kubeconfig=${SNAP_DATA}/credentials/kubelet.config
--cert-dir=${SNAP_DATA}/certs
--client-ca-file=${SNAP_DATA}/certs/ca.crt
--anonymous-auth=false
--network-plugin=cni
--root-dir=${SNAP_COMMON}/var/lib/kubelet
--fail-swap-on=false
--cni-conf-dir=${SNAP_DATA}/args/cni-network/
--cni-bin-dir=${SNAP}/opt/cni/bin/
--feature-gates=DevicePlugins=true
--eviction-hard="memory.available<100Mi,nodefs.available<1Gi,imagefs.available<1Gi"
--container-runtime=remote
--container-runtime-endpoint=${SNAP_COMMON}/run/containerd.sock
--node-labels="microk8s.io/cluster=true"
--runtime-cgroups=/systemd/system.slice
--kubelet-cgroups=/systemd/system.slice
--cluster-domain=cluster.local
--cluster-dns=10.152.183.10
```

**Comment by ktsakalozos** [comment]
It is hard to accept this PR because we will be adding entries for a registry that is not available. The user would still need to expose the dns entry of the hosted registry.

Have you tried the approach outlined in [1, 2] ?

[1] https://skaffold.dev/docs/environment/image-registries/
[2] https://odino.org/local-k8s-development-in-2020/

**Comment by SamyCoenen** [comment]
@ktsakalozos Alright, if the DNS entry is not acceptable then 2 options remain:
- Wait for this issue to be fixed https://github.com/GoogleContainerTools/skaffold/issues/2217
- Use Docker to build the images instead of Kaniko as suggested https://github.com/ubuntu/microk8s/pull/1122#issuecomment-617023823

**Comment by balchua** [comment]
I actually hit this issue too when working with kaniko.  I end up adding the host ip to the cri registry config.
Ex.
"192.168.1.1:32000"

Obviously expose the service via `NodePort`

**Comment by SamyCoenen** [comment]
@balchua 192.168.1.x/24 is a private network, it could be 172.16.x.x or 192.168.0.x for others every time they start their system so that is why I didn't go with that. It would work at my home network but not at work for example.

**Comment by balchua** [comment]
Absolutely right. Didn't thought about that scenario.

**Pull request closed without merging**
