### PR TITLE
upgrade calico to v3.19.1

### PR DESCRIPTION
**Pull request by balchua**
### Thank you for making MicroK8s better

This PR upgrade calico to v3.19.1.  No change is done when upgrading a cluster which is already using the previous calico.
This supersedes https://github.com/ubuntu/microk8s/pull/2081, and thanks to @danports for initiating the work.

*Also verify you have:*
* [X] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [X] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

@ktsakalozos thanks for taking a look at this.

### CODE REVIEW

**Comment by balchua** [comment]
@ktsakalozos 
I have to include the `export CGO_LDFLAGS_ALLOW="-Wl,-z,now"` to `snapcraft.yaml`.  Otherwise go-dqlite build fails.
Please let me know if this is ok.

**Comment by balchua** [comment]
The Lint Code failure is fix by this PR (https://github.com/ubuntu/microk8s/pull/2370)

**Comment by ktsakalozos** [comment]
This has to go in because in v1.22.0 the current calico manifest is failing with:
```
> microk8s.kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml 
configmap/calico-config unchanged
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrole.rbac.authorization.k8s.io/calico-node unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-node unchanged
daemonset.apps/calico-node configured
serviceaccount/calico-node unchanged
deployment.apps/calico-kube-controllers unchanged
serviceaccount/calico-kube-controllers unchanged
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "/var/snap/microk8s/current/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**Comment by ktsakalozos** [comment]
LGTM +1 thank you @balchua

**Comment by DjVinnii** [comment]
As stated by @balchua, Calico is not upgraded by upgrading an existing Microk8s cluster. In my case this was as easy as grabbing the latest [calico.yaml](https://github.com/ubuntu/microk8s/blob/master/upgrade-scripts/000-switch-to-calico/resources/calico.yaml), changing the `IP_AUTODETECTION_METHOD` and applying this yaml. However I wonder if the Calico upgrade process should be documented somewhere?

**Pull request merged**
