### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by sfstpala**
Changed `Would you like to do that it now?` to `Would you like to do that now?` in installer.

### CODE REVIEW

**Review by neoaggelos — APPROVED** [review]
Thanks for the fix @sfstpala!

**Review by ktsakalozos — APPROVED** [review]
LGTM +1

**Comment by ktsakalozos** [comment]
Thank you for this PR @sfstpala 

Could you please sign the CLA agreement at https://ubuntu.com/legal/contributors/agreement ?

**Review by joedborg — APPROVED** [review]
Thank  you!  LGTM.

**Comment by sfstpala** [comment]
Thanks all :)

CLA is signed (https://launchpad.net/~stefano-palazzo/+participation)

**Pull request merged**
