### PR TITLE
Added support for Knative (#320)

### PR DESCRIPTION
**Pull request by olatheander**
Added support for enabling/disabling Knative and implicitly also enabling Istio since Knative depends on it.

### CODE REVIEW

**Comment by balchua** [comment]
@olatheander i think your test is failing because it is looking for `activator-service`, when it should only be `activator`.

**Comment by olatheander** [comment]
@balchua Thanks for the feedback and you're correct. I have renamed to `activator`so let's see how Travis likes it now.

**Comment by ktsakalozos** [comment]
Thank you for this PR @olatheander . There are a few adjustment I will do in a followup PR.

There is a race condition in https://github.com/ubuntu/microk8s/pull/501/files#diff-7ea263c42dd785375276d6c28ab62355R32 where the second apply may fail because the CRDs are not applied yet. The result is that the enable will fail with: 
```
unable to recognize "/snap/microk8s/x1/actions/knative/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1"
unable to recognize "/snap/microk8s/x1/actions/knative/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1"
```

The travis tests are timing out so I will merge the knative and istio tests and have them running in our CI only.

**Comment by olatheander** [comment]
@ktsakalozos Thank you for the merge and the feedback regarding the race-condition. I try and look into it too.

Regarding the time-out of the tests that is something I'm looking into but have not yet a fix for but I have an idea for a solution. There is no particular reason why it should time out, i.e. the time it takes to wire up Istio + Knative is not in that magnitude. If it works out there will be another PR coming up.

**Comment by ktsakalozos** [comment]
@olatheander I pinged you over at the followup PR https://github.com/ubuntu/microk8s/pull/505 , let me know what you think.

**Pull request merged**
