### PR TITLE
Update microk8s.wrapper: avoid using `ls` that can produce different …

### PR DESCRIPTION
**Pull request by shoce**
I have a different output of `ls` in my system so i get a weird output. This change avoids using `ls` and uses bash path glob expansion instead. This should be more platform-independent.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Hi @shoce, could you please sign the CLA agreement https://ubuntu.com/legal/contributors/agreement ?

**Comment by shoce** [comment]
Yep i have it signed now

**Comment by joedborg** [comment]
Hi @shoce, can you confirm you signed it with the same email address as you committed with?  https://github.com/ubuntu/microk8s/pull/2392/checks?check_run_id=3012050588

**Comment by shoce** [comment]
> Hi @shoce, can you confirm you signed it with the same email address as you committed with? https://github.com/ubuntu/microk8s/pull/2392/checks?check_run_id=3012050588

I did it right now one more time, hope it will work. Just in case, when i submit the form on https://ubuntu.com/legal/contributors/agreement i get redirected to https://www.tfaforms.com/forms/view/... that has the same form (different style) asking me additionally for my launchpad id and stating that "The CAPTCHA was not completed successfully." though it was. So i filled that form on tfaforms.com and submitted it as well, successfully.

**Review by ktsakalozos — APPROVED** [review]
Thank you @shoce

**Pull request merged**
