### PR TITLE
Use hyphen instead of underscore

### PR DESCRIPTION
**Pull request by joedborg**
Keeps names consistent.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
To change this we will need to update our CI scripts in https://github.com/charmed-kubernetes/jenkins/blob/master/jobs/microk8s/snapstore.py#L149 and back port this rename to all branches since they go through jenkins.

**Comment by chris-sanders** [comment]
@joedborg actually I think we're going the wrong direction with this. test-distros isn't a valid python module name and pytest won't pickup tests in it. The files with pytests in it should actually use the underscore or they aren't valid for test discovery.

**Review by chris-sanders — CHANGES_REQUESTED** [review]
I think we're going the wrong direction with this. test-distros isn't a valid python module name and pytest won't pickup tests in it. The files with pytests in it should actually use the underscore or they aren't valid for test discovery.

**Comment by ktsakalozos** [comment]
> To change this we will need to update our CI scripts in https://github.com/charmed-kubernetes/jenkins/blob/master/jobs/microk8s/snapstore.py#L149 and back port this rename to all branches since they go through jenkins.

Ignore me, this is a different file.

**Pull request closed without merging**
