### PR TITLE
Enforce YAML formatting

### PR DESCRIPTION
**Pull request by joedborg**
Draft PR to start a discussion around this.  I believe our YAML should be enforced the same way that our Python is.

### CODE REVIEW

**Comment by joedborg** [comment]
Using [Prettier](https://prettier.io) as it's very opinionated and integrates with most editors.

**Review by knkski — APPROVED** [review]
LGTM, other than squashing commits before merging

**Comment by balchua** [comment]
LGTM. 👍

**Comment by ktsakalozos** [comment]
Still failing @joedborg . Maybe we should not enforce yaml style in the manifests?

**Comment by joedborg** [comment]
@ktsakalozos all passing now

**Pull request merged**
