### PR TITLE
Add hubble addon

### PR DESCRIPTION
**Pull request by joestringer**
Add support for hubble (https://github.com/cilium/hubble), a cluster
observability tool that runs on top of Cilium.

From the readme:

>  Hubble is a fully distributed networking and security observability
>  platform for cloud native workloads. It is built on top of Cilium and
>  eBPF to enable deep visibility into the communication and behavior of
>  services as well as the networking infrastructure in a completely
>  transparent manner.

This addon includes a graphical web UI that visualizes pods and their traffic
flows. At the end of the microk8s.enable command, microk8s.enable will present
the URL on which the UI can be accessed.

The hubble CLI can be accessed via a wrapper script, for example:

```
  $ microk8s.hubble observe
  TIMESTAMP             SOURCE
  DESTINATION                                            TYPE
  VERDICT     SUMMARY
  Dec 20 15:29:18.531   10.152.183.1:443(https)
  kube-system/coredns-9b8997588-nnghf:44202              to-endpoint
  FORWARDED   TCP Flags: ACK, PSH
  Dec 20 15:29:18.531   kube-system/coredns-9b8997588-nnghf:44202
  172.22.22.58:16443                                     to-host
  FORWARDED   TCP Flags: ACK
```

Example installation:

```
  Enabling Hubble
  Fetching hubble version master.
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   121    0   121    0     0    159      0 --:--:-- --:--:-- --:--:--   159
  100 9212k  100 9212k    0     0  1504k      0  0:00:06  0:00:06 --:--:-- 2059k
  Deploying /var/snap/microk8s/1109/actions/hubble.yaml. This may take several minutes.
  serviceaccount/hubble created
  serviceaccount/hubble-ui created
  clusterrole.rbac.authorization.k8s.io/hubble created
  clusterrole.rbac.authorization.k8s.io/hubble-ui created
  clusterrolebinding.rbac.authorization.k8s.io/hubble created
  clusterrolebinding.rbac.authorization.k8s.io/hubble-ui created
  service/hubble-grpc created
  service/hubble-ui created
  daemonset.apps/hubble created
  deployment.apps/hubble-ui created
  Waiting for daemon set "hubble" rollout to finish: 0 of 1 updated pods are available...
  daemon set "hubble" successfully rolled out
  Hubble is enabled with UI on http://10.244.122.242:12000
```

This currently pins hubble to the master branch / latest versions of
hubble as it is under active development. As the hubble project matures,
we expect to update this to follow semver. The HUBBLE_VERSION
environment variable supports overriding the version that is installed.

### CODE REVIEW

**Comment by balchua** [comment]
I believe hubble only works on amd64 arch.
Usually we remove addons which are not supported in a particular arch in `snapcraft.yaml` 

https://github.com/ubuntu/microk8s/blob/dbc90b6332ee0d96d94ebeaab044b2815adfe01f/snapcraft.yaml#L287

**Comment by joestringer** [comment]
Thanks @balchua, I've addressed your feedback.

**Comment by balchua** [comment]
Hi @joestringer thanks for adapting the changes the tests have been upgraded to `python3` and utilizes the markers such as `@skipif` constructs instead of adding conditional codes to test for `UNDER_TIME_PRESSURE`.  This males the CI tests cleaner and faster too.

If you merge in from master you should see some changes done on other tests.

**Comment by joestringer** [comment]
For now there are upstream discussions ongoing in Cilium community which may render this PR obsolete, so I will withdraw it for now. Users who want to try it out can use these scripts and I will plan to resubmit when the upstream discussions are resolved.

**Pull request closed without merging**
